import {useEffect, useState} from 'react';

// Generated by Github Copilot
export default function useAsync(asyncFunction: () => Promise<any>, deps: any[] = []) {
  const [data, setData] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    const fetchData = async () => {
      setIsLoading(true);
      const result = await asyncFunction();
      setData(result);
      setIsLoading(false);
    };
    fetchData();
  }, deps);

  return { data, isLoading };
}